version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - .:/proxy_app
    container_name: proxy_app_web_name
    ports:
      - "3003:3003"
    networks:
      - proxy_data_bridge
      - main_via_proxy_proxy_bridge
      - apps_monitoring_bridge
    external_links:
      - data_app_web_name:data_app_web_link
networks:
  proxy_data_bridge:
    external: true
  main_via_proxy_proxy_bridge:
    external: true
  apps_monitoring_bridge:
    external: true
