# Generates traffic for grafana testing purposes

main_via_proxy_one_app_request_url = 'http://localhost:3002/api/users_via_proxy_from_data_app'
main_via_proxy_two_app_request_url = 'http://localhost:3006/api/users_via_proxy_two_from_data_app'
main_direct_app_request_url = 'http://localhost:3001/api/users_directly_from_data_app'
# Proxy App and Data App require autogenerated auth header X-Origin-Auth which is not provided in the curl request below
# and thus they will be unauthorized \o/
unauthorized_proxy_app_request_url = 'http://localhost:3003/api/proxy_for_data_app'
unauthorized_data_app_request_url = 'http://localhost:3004/api/users'

100.times do
  request_url =
    [
      main_via_proxy_one_app_request_url,
      main_via_proxy_two_app_request_url,
      main_direct_app_request_url,
      unauthorized_proxy_app_request_url,
      unauthorized_data_app_request_url
    ].sample
  system("curl --silent --output /dev/null --header 'Accept: application/json' #{request_url}")
  print '.'
  sleep 10
end
