# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c59a837b8d3158f9c4e4deaeb6202f8075e4902bd3d6f86919b8a70823f8de4e0ead7051b310b219eb48eb84022708c4a8c403ad4edf4e3ac46cc8474714ffe
  jwt:
    secret: 'soverysecret'
test:
  secret_key_base: 83d66f73bb5314a73b3068333016d01a16cebfa15635eb675658cdbf44c5bbf0b6853433f839d44f92799535414219025aebde17355ad40c50da8b91df67f54f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
